export const products = [
  {
    id: 1,
    name: "Product Name",
    labels: ["Label", "Label"],
    rating: 4,
    price: "000 QAR",
    oldPrice: "000 QAR",
    description: "A limited quantity of the product is left",
    available: 20,
    total: 100,
    availableText: "00Kg",
  },
  {
    id: 2,
    name: "Product Name",
    labels: ["Label", "Label"],
    rating: 4,
    price: "000 QAR",
    oldPrice: "000 QAR",
    description: "A limited quantity of the product is left",
    available: 30,
    total: 100,
    availableText: "00Kg",
  },
  {
    id: 3,
    name: "Product Name",
    labels: ["Label", "Label"],
    rating: 4,
    price: "000 QAR",
    oldPrice: "000 QAR",
    description: "A limited quantity of the product is left",
    available: 40,
    total: 100,
    availableText: "00Kg",
  },
  {
    id: 4,
    name: "Product Name",
    labels: ["Label", "Label"],
    rating: 4,
    price: "000 QAR",
    oldPrice: "000 QAR",
    description: "A limited quantity of the product is left",
    available: 50,
    total: 100,
    availableText: "00Kg",
  },
  {
    id: 5,
    name: "Premium Quality Product",
    labels: ["Premium", "New"],
    rating: 5,
    price: "1200 QAR",
    oldPrice: "1500 QAR",
    description: "High quality premium product available",
    available: 15,
    total: 100,
    availableText: "02Kg",
  },
  {
    id: 6,
    name: "Organic Fresh Product",
    labels: ["Organic", "Fresh"],
    rating: 3,
    price: "800 QAR",
    oldPrice: "900 QAR",
    description: "Fresh organic product for healthy living",
    available: 60,
    total: 100,
    availableText: "05Kg",
  },
  {
    id: 7,
    name: "Limited Edition Special",
    labels: ["Limited", "Special"],
    rating: 5,
    price: "2000 QAR",
    oldPrice: "2200 QAR",
    description: "Exclusive limited edition product",
    available: 10,
    total: 100,
    availableText: "01Kg",
  },
  {
    id: 8,
    name: "Budget Friendly Option",
    labels: ["Budget", "Sale"],
    rating: 2,
    price: "400 QAR",
    oldPrice: "500 QAR",
    description: "Affordable product for everyone",
    available: 80,
    total: 100,
    availableText: "10Kg",
  },
];

export default products;